version: "3.8"

services:
  db_bautista:
    image: mysql:8
    container_name: db_bautista
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: HanniaStrongP@ssw0rd
      MYSQL_DATABASE: hannia_bautista_db
      MYSQL_USER: hannia_user
      MYSQL_PASSWORD: hannia
    volumes:
      - db_bautista_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - appnet

  backend_bautista:
    build:
      context: ./backend-bautista
      dockerfile: Dockerfile
    container_name: backend_bautista
    restart: unless-stopped
    depends_on:
      - db_bautista
    environment:
      DB_HOST: db_bautista
      DB_PORT: 3306
      DB_USER: hannia_user
      DB_PASSWORD: hannia
      DB_NAME: hannia_bautista_db
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend_hannia:
    build:
      context: ./frontend-hannia
      dockerfile: Dockerfile
    container_name: frontend_hannia
    restart: unless-stopped
    depends_on:
      - backend_bautista
    environment:
      REACT_APP_API_URL: http://backend_bautista:5000
    ports:
      - "3000:3000"
    networks:
      - appnet

volumes:
  db_bautista_data:

networks:
  appnet:
    driver: bridge
  